name: Slack Notify

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  semgrep-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install jq and curl
        run: sudo apt-get update && sudo apt-get install -y jq curl
      
      - name: Read Semgrep Report and Check Severity
        id: check_severity
        run: |
          CRITICAL_COUNT=$(jq '[.[] | select(.Severity=="Critical" or .Severity=="High")] | length' reports/semgrep-report-blog-app.json)
          echo "Found $CRITICAL_COUNT critical/high issues"
          echo "::set-output name=critical_count::$CRITICAL_COUNT"
      
      - name: Notify Slack If Vulnerabilities Found
        run: |
          if [ "${{ steps.check_severity.outputs.critical_count }}" -ne 0 ]; then
            curl -X POST -H 'Content-type: application/json' --data '
            {
              "attachments": [
                {
                  "color": "#FF0000",
                  "title": "Critical Vulnerabilities Detected by Semgrep",
                  "text": "'${{ github.repository }} has ${{ steps.check_severity.outputs.critical_count }} high/critical issues.",
                  "fields": [
                    { "title": "PR", "value": "'${{ github.event.pull_request.html_url }}'" }
                  ]
                }
              ]
            }' ${{ secrets.SLACK_WEBHOOK_URL }}
          fi
        env:
          SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
