name: Slack Notify

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  semgrep-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install jq and curl
        run: sudo apt-get update && sudo apt-get install -y jq curl
      
      - name: Read Semgrep Report and Check Severity
        id: check_severity
        run: |
          CRITICAL_COUNT=$(jq '[.[] | select(.Severity=="Critical" or .Severity=="High")] | length' reports/semgrep-report-blog-app.json)
          echo "Found $CRITICAL_COUNT critical/high issues"
          echo "CRITICAL_COUNT=$CRITICAL_COUNT" >> $GITHUB_ENV
      
      - name: Notify Slack If Vulnerabilities Found
        if: env.CRITICAL_COUNT != '0'
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          fields: repo,workflow,job
          custom_payload: |
            {
              "attachments": [
                {
                  "color": "#FF0000",
                  "title": "Critical Vulnerabilities Detected by Semgrep",
                  "text": "${{ github.repository }} has ${{ env.CRITICAL_COUNT }} high/critical issues."
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
