name: Semgrep Scan and PR Block

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  pull-requests: write

jobs:
  semgrep-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq curl

      - name: Read Semgrep Report and Check Severity
        id: check_severity
        run: |
          echo "Reading report from reports/semgrep-report-blog-app.json"
          if [[ ! -f reports/semgrep-report-blog-app.json ]]; then
            echo "Report file not found!"
            exit 1
          fi

          # Hitung jumlah temuan High dan Critical severity dalam report JSON  
          high_count=$(jq '[.[] | select(.Severity == "High")] | length' reports/semgrep-report-blog-app.json)
          critical_count=$(jq '[.[] | select(.Severity == "Critical")] | length' reports/semgrep-report-blog-app.json)

          echo "High severity findings count = $high_count"
          echo "Critical severity findings count = $critical_count"

          total=$((high_count + critical_count))
          
          # Set output untuk langkah berikutnya  
          echo "::set-output name=total_findings::$total"

      - name: Send Slack Notification if High or Critical Findings Found
        if: steps.check_severity.outputs.total_findings != '0'
        env:
          SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
        run: |
          payload="{
            \"text\": \":warning::warning::warning:\n*Semgrep Scan Alert*\nFound *${{ steps.check_severity.outputs.total_findings }}* High/Critical vulnerabilities in the latest scan.\nPlease review the report at your earliest convenience.\"
           }"
          
           curl -X POST --data-urlencode "payload=$payload" "$SLACK_WEBHOOK_URL"

      - name : Fail workflow if High or Critical Findings Found to block PR merge 
        if : steps.check_severity.outputs.total_findings != '0'
        run : |
           echo "::error ::Found high or critical vulnerabilities, blocking merge."
           exit 1
